file_dir_names:
  data_filename: "data/cost_ribbon_Kolchuga.csv"
  output_fig_filename: "MOP_emin_dn315.pdf"
  figures_dirname: "figures"

settings_for_figures:
  background_color_fig: "#FDFDFD"
  PE_color: "#2a2aa6"
  Kolchuga_2mm_color: "#a62a2a"
  Kolchuga_4mm_color: "#2aa62a"
  vertic_lines_point_color: "#C9D6DF"
  black_color: "#303841"
  margin_left: 0.00035
  margin_right: 0.00035
  text_offset_x: 0.9
  text_offset_y: 1.02
  y_uplim_left: 2.7
  y_step_left: 0.25
  y_uplim_right: 12300
  y_step_right: 500

input_data_for_compute:
  MOP_normative: 2.00
  e_SDR: 0.0352
  dn: 0.315
  ro_PE: 954
  price_PE: 120
  l_pipe: 1
  MRS: 10.0
  c0: 2
  c1: 3.2
  k_2mm: 1.98
  k_4mm: 2.35
  xvalue_SDR: [0.0121, 0.0150, 0.0179, 0.0187, 0.0232, 0.0286, 0.0352]
  xlabel_SDR: ["SDR 26", "SDR 21", "", "SDR 17", "SDR 13.6", "SDR 11", "SDR 9"]
