---
# *** MENU ***
# Types of ACF (for `kind_acf`):
# 1: exp type,
# 2: exp-cos type,
# 3: exp-cos-sin type (plus),
# 4: exp-cos-sin type (minus)

# *** MAIN CONTROL PARAMETERS ***
sigma: !!float 2            # standard deviation
w_star: !!float 2.5        # model parameter
w0: !!float 8             # model parameter
alpha: !!float 0.05         # smoothing factor for EWMA
window_width: !!int 14  # width of window in MA
delta_t: !!float 0.05       # time step
N: !!int 1000               # number of counts
kind_acf: !!int 3           # ACF type


# *** OTHERS APP SETTINGS ***
visibility:
  ma_show: !!bool true

colors:
  white: !!str &white "#FDFDFD"
  grey: !!str &grey "#52616B"
  blue_purple: !!str &blue_purple "#8785A2"
  terakotta: !!str &terakotta "#E84A5F"
  pearl_night: !!str &pearl_night "#112D4E"
  krayola_green: !!str &krayola_green "#1CAC78"

figure_settings:
  height_main_fig: !!int 7
  width_main_fig: !!int 18
  left_xlim_acf: !!float 0.
  right_xlim_acf: !!float 4.
  left_xlim_pdf: !!float -9
  right_xlim_pdf: !!float 9
...
